// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/quickjpeg.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class QuickjpegBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  QuickjpegBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  QuickjpegBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// A very short-lived native function.
  ///
  /// For very short-lived functions, it is fine to call them on the main isolate.
  /// They will block the Dart execution while running the native function, so
  /// only do this for native functions which are guaranteed to be short-lived.
  int sum(int a, int b) {
    return _sum(a, b);
  }

  late final _sumPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>('sum');
  late final _sum = _sumPtr.asFunction<int Function(int, int)>();

  int init() {
    return _init();
  }

  late final _initPtr = _lookup<ffi.NativeFunction<ffi.Int Function()>>('init');
  late final _init = _initPtr.asFunction<int Function()>();

  /// Compresses separate YUV planes (YUV420)
  Span compress_image(
    ffi.Pointer<ffi.Uint8> y,
    int y_len,
    int y_stride,
    ffi.Pointer<ffi.Uint8> u,
    int u_len,
    int u_stride,
    ffi.Pointer<ffi.Uint8> v,
    int v_len,
    int v_stride,
    int width,
    int height,
  ) {
    return _compress_image(
      y,
      y_len,
      y_stride,
      u,
      u_len,
      u_stride,
      v,
      v_len,
      v_stride,
      width,
      height,
    );
  }

  late final _compress_imagePtr =
      _lookup<
        ffi.NativeFunction<
          Span Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Int,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Int,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('compress_image');
  late final _compress_image = _compress_imagePtr
      .asFunction<
        Span Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          int,
          int,
        )
      >();

  /// Converts NV12 to XRGB and compresses that
  Span compress_nv12(
    ffi.Pointer<ffi.Uint8> dest,
    int dest_stride,
    ffi.Pointer<ffi.Uint8> y,
    int y_len,
    int y_stride,
    ffi.Pointer<ffi.Uint8> uv,
    int uv_len,
    int uv_stride,
    int width,
    int height,
  ) {
    return _compress_nv12(
      dest,
      dest_stride,
      y,
      y_len,
      y_stride,
      uv,
      uv_len,
      uv_stride,
      width,
      height,
    );
  }

  late final _compress_nv12Ptr =
      _lookup<
        ffi.NativeFunction<
          Span Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Int,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('compress_nv12');
  late final _compress_nv12 = _compress_nv12Ptr
      .asFunction<
        Span Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          int,
          int,
        )
      >();

  Span compress_rgb(
    ffi.Pointer<ffi.Uint8> src,
    int src_stride,
    int width,
    int height,
  ) {
    return _compress_rgb(src, src_stride, width, height);
  }

  late final _compress_rgbPtr =
      _lookup<
        ffi.NativeFunction<
          Span Function(ffi.Pointer<ffi.Uint8>, ffi.Int, ffi.Int, ffi.Int)
        >
      >('compress_rgb');
  late final _compress_rgb = _compress_rgbPtr
      .asFunction<Span Function(ffi.Pointer<ffi.Uint8>, int, int, int)>();

  /// A longer lived native function, which occupies the thread calling it.
  ///
  /// Do not call these kind of native functions in the main isolate. They will
  /// block Dart execution. This will cause dropped frames in Flutter applications.
  /// Instead, call these native functions on a separate isolate.
  int sum_long_running(int a, int b) {
    return _sum_long_running(a, b);
  }

  late final _sum_long_runningPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int, ffi.Int)>>(
        'sum_long_running',
      );
  late final _sum_long_running = _sum_long_runningPtr
      .asFunction<int Function(int, int)>();
}

final class Span extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> data;

  @ffi.Size()
  external int len;
}
